Update libs.versions.toml
micronaut-projects/micronaut-gradle-plugin pull request #951
Opened 2024-03-01 07:51 UTC by shekarroy15

log4j zero day is long gone and the project is in stabler versions

2024-03-01 07:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-gradle-plugin?pullRequest=951) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-gradle-plugin?pullRequest=951) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-gradle-plugin?pullRequest=951) it.</sub>

2024-03-01 09:57 UTC, melix requested changes
Thanks! the version needs to be put in double quotes

2024-03-01 10:34 UTC, shekarroy15 commented
> Thanks! the version needs to be put in double quotes

i am sorry, dint realize then :(

2024-03-01 10:35 UTC, melix approved these changes

2024-03-21 15:57 UTC, merged

2024-03-21 16:16 UTC, timyates commented
Thanks @shekarroy15 ! 😎